### ISSUE TITLE
Deleted all Enemies, want to undo without creating a new save.

### ISSUE THREAD

**Issue by tezguin** [Goz3rr/SatisfactorySaveEditor#175]
Is it possible to undo the Delete Enemies cheat? I looked through the EnemySpawner tree and was trying to find what the cheat changed and couldn't see anything different.

**Comment by Ryder17z** [comment]
I'm not sure how it works but it can either be reversed by adding spawn points if they were removed or reset the flags if they were changed.

These options are only suitable if there's no global flag for creature spawn points. I have not looked into how the cheat works, but it's likely to be one of the three

**Comment by Goz3rr** [comment]
The way the cheat works is by moving all spawners down 50000 units, sets WasKilled to true and KilledOnDayNumber to a large number. I don't exactly remember why it moves the spawners under the world too, but technically all of these can be undone assuming you didn't accidentally run the cheat multiple times and no new spawners have been added to the game since.

I'll look into adding a way to reverse it but it's all a bit hacky at this point

**Comment by Ryder17z** [comment]
you could add 50000 units to the the position multiple times to reset it if necessary, there just needs to be some reference height so you don't go too high up

**Comment by tezguin** [comment]
Sorry about the delay in my response. Im looking through the save file and noticing a whole lot of weirdness, im probably just gonna start fresh.

**Comment by Goz3rr** [comment]
Undo cheat was added in v0.9.8
