### ISSUE TITLE
W32/Exploit.gen when running latest download

### ISSUE THREAD

**Issue by cliveflint** [Goz3rr/SatisfactorySaveEditor#176]
Hi,

I just downloaded the latest zip file and Panda reported W32/Exploit.gen in appdata\Local\Temp\...\SourceCodemessage.exe

**Comment by Ryder17z** [comment]
Sorry but Panda is one of the AV's you generally do not want to run due to various issues.
This is a"false positive" and Panda can be really strange sometimes. Especially when a zip, exe or msi file is downloaded but 0.1% of the file is missing. 

You should redownload the zip and it should be fine.
You can check the file yourself at https://www.virustotal.com/gui/file/1c063c5f39f0b27b17d150b22313b54637b56bc3b5a3ec351dd54f39e51f567a/detection

You can read more about this particular issue here: https://blog.malwarebytes.com/security-world/2017/09/explained-false-positives/ as it doesn't matter what AV you use, there's almost always a risk of it blocking something because the AV can only guess from what it has been trained on. **This can happen to any antivirus.**

**Comment by Goz3rr** [comment]
Thanks for explaining it @Ryder17z 

This isn't anything we can fix, you can contact the developers of your antivirus to report a false positive.

As a side note, if you were trying to run the editor you downloaded the wrong zip and should visit the [releases](https://github.com/Goz3rr/SatisfactorySaveEditor/releases) page instead.
