### ISSUE TITLE
Add option in cheat shortcuts to remove destructible rocks

### ISSUE THREAD

**Issue by KingOfTac** [Goz3rr/SatisfactorySaveEditor#43]
A nice addition would be to remove all destructible rocks although with the sulfur research chain coming out by the end of the month, it may not be very useful.

**Comment by bro15047** [comment]
Could possibly use similar properties as the foliage removal script.

**Comment by budak7273** [comment]
I think this would be helpful. I'm sure some people will want to do this even once sulfur comes out. I am busy this week and won't be able to work on it personally, but I'll let you know if this feature gets added.

**Comment by atehxx** [comment]
Some hints what I already checked:
Removing Entries containing 'BP_DestructibleLargeRock' didn't remove the rocks.
Changing position Z of them to -300000 did the trick :)

**Comment by bro15047** [comment]
Hmm, didn’t think about just moving them, I’ll definitely have to try it.

**Comment by bro15047** [comment]
@budak7273  It looks like when you use the C4 to destroy rocks it just deletes the entity from the list of rocks, so I think removing rocks from inside the editor should be possible after issue #39 is resolved.

**Comment by atehxx** [comment]
Some more info I leave here which might help you:
I wanted to delete all Slugs from save (a.k.a. Crystals) but same thing happened as with Rocks - they were back when I loaded the save again (and trick with moving them didn't work). Turns out game regenerates those removed entities. And I found why - they are not on UnknownMap list - it is used to remove from map stuff that player picked up. So to delete Slugs from save I had to both remove entities, and also add references in UnknownMap list. This worked. I believe same procedure will work for Rocks.
On this UnknownMap list there are also Berries, Bushes, etc.
